/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status: "ok";
                            uptime: number;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/coach/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        age: number;
                        /** @enum {string} */
                        sex: "male" | "female";
                        heightCm: number;
                        weightKg: number;
                        bodyFatPct?: number;
                        /** @enum {string} */
                        primaryGoal: "hypertrophy" | "pure_strength" | "gymnastics_skills" | "athletic_performance" | "fat_loss" | "longevity_health";
                        /** @enum {string} */
                        experienceLevel: "beginner" | "intermediate" | "advanced";
                        trainingDaysPerWeek: number;
                        equipment: ("barbell" | "dumbbell" | "machine" | "cables" | "kettlebell" | "bodyweight" | "rings")[];
                        /** @default [] */
                        limitationsOrInjuries?: string[];
                        currentDietStyle?: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            physiologicalProfile: {
                                /** @description Calculated TDEE based on physical details */
                                estimatedTdee: number;
                                /** @description Calculated if body fat percent was provided */
                                leanBodyMassKg: number | null;
                                /** @description Mechanical alignment warnings or levers assessment based on constraints */
                                biomechanicalObservations: string;
                            };
                            periodizedNutrition: {
                                /** @description Scientific critique of why generic named diets might fail this objective */
                                generalStanceOnNamedDiets: string;
                                macronutrientTargets: {
                                    calories: number;
                                    /** @description Target matching 1.6-2.2 g/kg (or lean-mass adjusted) */
                                    proteinGrams: number;
                                    /** @description Periodized to training volume */
                                    carbohydratesGrams: number;
                                    /** @description Remainder calories, kept away from peri-workout windows */
                                    fatsGrams: number;
                                };
                                periWorkoutProtocol: {
                                    preWorkoutMeal: string;
                                    intraWorkoutHydrationAndNutrition: string;
                                    postWorkoutMeal: string;
                                };
                                nonTrainingDayAdjustments: string;
                            };
                            trainingProgram: {
                                /** @description e.g. Push/Pull/Legs, Upper/Lower, Full Body */
                                splitName: string;
                                /** @description Scientific reason for this split and frequency */
                                frequencyRationale: string;
                                weeklyLayout: {
                                    dayNumber: number;
                                    focus: string;
                                    exercises: {
                                        name: string;
                                        sets: number;
                                        /** @description e.g. "3-5", "8-12", "5s hold" */
                                        reps: string;
                                        /** @description Reps in Reserve */
                                        rirTarget: number;
                                        restSeconds: number;
                                        /** @description Cue bridging lab to gym (biomechanics, tempo, or safety) */
                                        coachingCue: string;
                                    }[];
                                }[];
                            };
                            gymnasticsAndSkillWork: {
                                /** @description Per Overcoming Gravity: scapular/wrist/hollow prep */
                                straightArmPrep: string;
                                progressionAdvice: string;
                            } | null;
                            evidenceCitations: {
                                topic: string;
                                /** @description The physiological 'why' */
                                scientificMechanism: string;
                                /** @description Author or textbook from the core literature */
                                leadingReference: string;
                            }[];
                            /** @description Must address every raised safety flag; empty only if no flags and no injuries */
                            safetyNotes: string[];
                            reasoningText?: string;
                            reasoningTokens?: number | null;
                        };
                    };
                };
                /** @description Default Response */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            issues: string[];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/coach/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        prompt: string;
                        profile?: {
                            age?: number;
                            /** @enum {string} */
                            sex?: "male" | "female";
                            heightCm?: number;
                            weightKg?: number;
                            bodyFatPct?: number;
                            /** @enum {string} */
                            primaryGoal?: "hypertrophy" | "pure_strength" | "gymnastics_skills" | "athletic_performance" | "fat_loss" | "longevity_health";
                            /** @enum {string} */
                            experienceLevel?: "beginner" | "intermediate" | "advanced";
                            trainingDaysPerWeek?: number;
                            equipment?: ("barbell" | "dumbbell" | "machine" | "cables" | "kettlebell" | "bodyweight" | "rings")[];
                            /** @default [] */
                            limitationsOrInjuries?: string[];
                            currentDietStyle?: string;
                        };
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            text: string;
                            steps: number;
                            reasoningText?: string;
                            usage: {
                                inputTokens: number | null;
                                outputTokens: number | null;
                                reasoningTokens?: number | null;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/coach/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        messages: ({
                            /** @description Client-generated message id. */
                            id?: string;
                            /** @enum {string} */
                            role: "system" | "user" | "assistant";
                            parts: ({
                                /** @description Part type, e.g. "text". */
                                type: string;
                                /** @description Present for text parts. */
                                text?: string;
                            } & {
                                [key: string]: unknown;
                            })[];
                        } & {
                            [key: string]: unknown;
                        })[];
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
